{{ if and .Values.redisDumpUri .Values.redis.persistence.existingClaim }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{- include "tranql.fullname"  . }}-seed-db-job"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{- include "tranql.fullname"  . }}-seed-db-job"
    spec:
      restartPolicy: Never
      containers:
        - name: init-db
          image: busybox
          command:
            - "wget"
          args:
            - "{{ .Values.redisDumpUri }}"
            - "-O"
            - "/data/dump.rdb"
          volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
        - name: "redis-data"
          persistentVolumeClaim:
            claimName: {{ include "redis.tplValue" (dict "value" .Values.redis.persistence.existingClaim "context" $) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis.tplValue" (dict "value" .Values.redis.persistence.existingClaim "context" $) }}
  annotations:
    "helm.sh/hook": pre-install
    # makes sure that pvc is created before job.
    "helm.sh/hook-weight": "-6"
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteMany
{{- end }}